# markdownlint-cli2 configuration tuned for the Obsidian vault

# Enable the default ruleset then selectively disable items that conflict with vault style
config:
  default: true
  MD013: false            # allow long lines
  MD033: true             # permit inline HTML
  MD041: false            # skip first-heading requirement
  MD026: false            # allow punctuation at end of headings
  MD034: false            # allow bare URLs
  MD025:                  # treat front matter as satisfying the top heading
    front_matter_title: ""
    level: 2
  MD004:
    style: consistent
  MD007:
    indent: 4
  MD051: false
  MD001: false
  MD036: false
