version: '3'

tasks:
  lint:
    desc: Run Ruff and markdownlint on the repository
    cmds:
      - direnv exec . ruff check
      - direnv exec . npx --yes markdownlint-cli2 --config .markdownlint-cli2.yaml

  format:
    desc: Format Python and Markdown sources
    cmds:
      - direnv exec . ruff format
      - direnv exec . npx --yes prettier --write "**/*.md"
      - direnv exec . npx --yes markdownlint-cli2 --config .markdownlint-cli2.yaml --fix

  test:
    desc: Execute pytest suite
    cmds:
      - direnv exec . env PYTHONPATH=. pytest

  check:
    desc: Run lint and tests together
    deps: [lint]
    cmds:
      - task: test

  clean:
    desc: Remove virtualenvs, caches, and build artifacts
    cmds:
      - rm -rf .venv .mypy_cache .pytest_cache dist build
      - find . -name '__pycache__' -type d -prune -exec rm -rf {} +
      - rm -rf tools/vault/extracted
