# @format

name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff pytest

      - name: Install Node-based tooling
        run: |
          npm install --global markdownlint-cli2 prettier

      - name: Ruff lint
        run: ruff check

      - name: Ruff format check
        run: ruff format --check

      - name: Markdownlint
        run: |
          npx --yes markdownlint-cli2 "**/*.md" "!node_modules"

      - name: Pytest
        env:
          PYTHONPATH: .
        run: pytest
